[package]
name = "rotaNotifier"
version = "0.1.0"
authors = ["Alex Chadwick <alexchadwick@outlook.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
